### ISSUE TITLE
Focus Dataset Suggestions

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/gdphelper#10]
Please submit a suggestion for a more dataset focused approach for the package.

**Comment by gfairbro** [comment]
As i reviewed the Economic datasets on the Open Canada site, i noticed 42 records referencing "[GDP at basic prices.](https://open.canada.ca/data/en/dataset/dc5c4808-ef54-41c9-9a65-e99e89fe673a)" They share the same featured columns, but are split across geography, industry, percentage or gross. I think there may be a fit to create an EDA pipeline that can take these datasets and generate visualizations that adjust depending on the data inputted. It would be a little different from what we originally spelled out, in that the functions might break down differently. Not much need for data cleaning as far as i can tell, but we might want to write several functions which run depending on the type of GDP data inputted.

**Comment by gfairbro** [comment]
There appears to be a similar opportunity with '[Labour Force by X](https://open.canada.ca/data/en/dataset/4407c827-8a7c-4877-5b94-9bc9f2b4cfb6)' data.

**Comment by GloriaWYY** [comment]
I looked through the example project repos from last year. A lot of them were dealing with EDA but without targetting at a specific type of datasets, so we might end up being creative in the dataset-oriented package developing way. 😍

As I examined some datasets on Open Canada website, I found some common characteristics in these data:

1. All features are of string type no matter it is truly character or numeric data. **Thoughts:** We might want a function to transform the data type as requested by the user. 
2. All datasets have their first 2 columns being `REF_DATE` which contains the year of record, and `GEO` which contains the region of the record. **Thoughts:** I am thinking that if we can have a dataset-comparing function that takes in two datasets, and compares the year scope or the region covered in these two datasets, so that a user can easily compare these pieces of information.

Datasets I looked at:
[second-hand smoke](https://open.canada.ca/data/en/dataset/555dd535-79aa-4416-8f5c-abe087a4e018)
[Organic products for sale](https://open.canada.ca/data/en/dataset/315411eb-37ec-459d-b9e1-dae096cb26a0)
[mortality rates](https://open.canada.ca/data/en/dataset/54aeef61-14ae-4221-8a58-f678dcfbe94b)

**Comment by RamiroMejia** [comment]
Hi guys,

I was checking a cool package called  `pandas_datareader` 

https://pandas-datareader.readthedocs.io/en/latest/

I was doing some tests today and I created a quick example of what we can do using financial data (bitcoins). 

I will share on the Slack the channel a jupyter notebook with two functions that I created.

**Comment by gfairbro** [comment]
We have landed on using the GDP in basic dollars dataset. See updated README for more details
